/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    ContextMenu: typeof import('primevue/contextmenu')['default']
    CreateNotebook: typeof import('./src/components/modal/CreateNotebook.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Editor: typeof import('./src/components/editor/Editor.vue')['default']
    InputRichText: typeof import('./src/components/editor/InputRichText.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ListSelect: typeof import('./src/components/ListSelect.vue')['default']
    PageTabs: typeof import('./src/components/PageTabs.vue')['default']
    Panel: typeof import('./src/components/Panel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    StepPanel: typeof import('primevue/steppanel')['default']
    StepPanels: typeof import('primevue/steppanels')['default']
    Stepper: typeof import('primevue/stepper')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    Tree: typeof import('./src/components/Tree.vue')['default']
    TreeNode: typeof import('./src/components/TreeNode.vue')['default']
  }
}
