/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    ContextMenu: typeof import('primevue/contextmenu')['default']
    CreateNotebook: typeof import('./src/components/modal/CreateNotebook.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    EditorFindAndReplace: typeof import('./src/components/editor/EditorFindAndReplace.vue')['default']
    EditorFloatMenu: typeof import('./src/components/editor/EditorFloatMenu.vue')['default']
    EditorStatus: typeof import('./src/components/editor/EditorStatus.vue')['default']
    EditorTools: typeof import('./src/components/editor/EditorTools.vue')['default']
    FloatPanel: typeof import('./src/components/FloatPanel.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ListSelect: typeof import('./src/components/ListSelect.vue')['default']
    PageTabs: typeof import('./src/components/PageTabs.vue')['default']
    Panel: typeof import('./src/components/Panel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    StepPanel: typeof import('primevue/steppanel')['default']
    StepPanels: typeof import('primevue/steppanels')['default']
    Stepper: typeof import('primevue/stepper')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    Tree: typeof import('./src/components/Tree.vue')['default']
    TreeNode: typeof import('./src/components/TreeNode.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
