name: Release Windows App

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag'
        required: true
        default: '1.0.0'

jobs:
  release:
    name: Release Windows App
    runs-on: windows-latest
    strategy:
      matrix:
        platform:
          - windows/amd64

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: latest
          run_install: true

      - name: build app
        shell: bash
        run: |
          pnpm run build:app

      - name: build nw
        shell: bash
        run: |
          pnpm run build:nw
          
